# Generated by Django 5.2.17 on 2026-10-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_account_preferences"),
        ("countries", "0003_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountpreferences",
            name="home_currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="countries.currency",
            ),
        ),
    ]
