# Generated by Django 5.2.17 on 2026-10-04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_account_preferences_home_currency"),
        ("countries", "0003_city"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentFeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "fx_markup_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "source_fixed_fee",
                    models.DecimalField(decimal_places=12, default=0, max_digits=40),
                ),
                (
                    "destination_fixed_fee",
                    models.DecimalField(decimal_places=12, default=0, max_digits=40),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="countries.currency",
                    ),
                ),
                (
                    "source_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="countries.currency",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_fee_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "name"),
                        name="unique_user_payment_fee_profile_name",
                    ),
                    models.CheckConstraint(
                        condition=~models.Q(("source_currency", models.F("destination_currency"))),
                        name="payment_fee_profile_currencies_differ",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("fx_markup_percent__gte", 0),
                            ("fx_markup_percent__lte", 25),
                        ),
                        name="payment_fee_profile_markup_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source_fixed_fee__gte", 0),
                            ("source_fixed_fee__lte", 1000000000),
                        ),
                        name="payment_fee_profile_source_fee_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("destination_fixed_fee__gte", 0),
                            ("destination_fixed_fee__lte", 1000000000),
                        ),
                        name="payment_fee_profile_destination_fee_range",
                    ),
                ],
            },
        ),
    ]
