# Generated by Django 5.2.17 on 2026-10-04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_budget_preset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[("pre_trip", "Pre-trip reminder")],
                        max_length=24,
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("timezone_name", models.CharField(default="UTC", max_length=64)),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("once", "Once when due"),
                            ("daily", "Daily while due"),
                        ],
                        default="once",
                        max_length=16,
                    ),
                ),
                ("lead_days", models.PositiveSmallIntegerField(default=3)),
                (
                    "delivery_channel",
                    models.CharField(
                        choices=[("in_app", "In-app")],
                        default="in_app",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("notification_type", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "notification_type"),
                        name="unique_user_notification_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("lead_days__gte", 1),
                            ("lead_days__lte", 30),
                        ),
                        name="notification_preference_lead_days_range",
                    ),
                ],
            },
        ),
    ]
