# yaml-language-server: $schema=https://render.com/schema/render.yaml.json

services:
  - type: web
    name: cultural-currency-converter-mykola
    runtime: python
    plan: free
    region: frankfurt
    branch: master
    buildCommand: bash scripts/render-build.sh
    startCommand: bash scripts/render-start.sh
    healthCheckPath: /health/ready/
    autoDeployTrigger: checksPass
