from __future__ import annotations

import re
from dataclasses import dataclass
from enum import StrEnum

from apps.culture.explore import ExploreDestination
from apps.culture.services import DestinationContext
from apps.exchange.ai.contracts import (
    ExplanationInsight,
    ExplanationPacket,
    ExplanationResult,
    GroundedFact,
)

PACKET_VERSION = "explore-destination:v1"

_DATE_RE = re.compile(r"\b\d{4}-\d{2}-\d{2}\b")
_NUMBER_RE = re.compile(r"(?<![\w-])[-+]?\d+(?:[.,]\d+)?(?![\w-])")
_UPPERCASE_RE = re.compile(r"\b[A-Z]{3}\b")


class ExploreExplanationIntent(StrEnum):
    OVERVIEW = "explore_overview"
    EVIDENCE = "explore_evidence"


class ExploreExplanationIntentError(ValueError):
    pass


@dataclass(frozen=True, slots=True)
class ExploreExplanationIntentSpec:
    intent: ExploreExplanationIntent
    label: str
    question: str
    focus_instruction: str
    required_fact_ids: tuple[str, ...]


_SPECS = {
    ExploreExplanationIntent.OVERVIEW: ExploreExplanationIntentSpec(
        intent=ExploreExplanationIntent.OVERVIEW,
        label="What matters here?",
        question="What matters most in this reviewed destination money context?",
        focus_instruction=(
            "Summarize only the reviewed destination facts in SOURCE_PACKET. Prioritize the "
            "current currency, available local-price scope and payment context. Do not compare "
            "this destination with another place or infer affordability."
        ),
        required_fact_ids=("destination_identity", "reference_scope"),
    ),
    ExploreExplanationIntent.EVIDENCE: ExploreExplanationIntentSpec(
        intent=ExploreExplanationIntent.EVIDENCE,
        label="How should I read this evidence?",
        question="How should I read the scope and freshness of these reviewed facts?",
        focus_instruction=(
            "Explain only the supplied review date, city/national scope and evidence boundary. "
            "Do not turn local price anchors into a cost-of-living index, purchasing-power claim "
            "or ranking."
        ),
        required_fact_ids=("as_of", "reference_scope"),
    ),
}


def explore_explanation_intent_spec(
    intent: ExploreExplanationIntent,
) -> ExploreExplanationIntentSpec:
    return _SPECS[intent]


def available_explore_explanation_intents() -> tuple[ExploreExplanationIntentSpec, ...]:
    return tuple(_SPECS[intent] for intent in ExploreExplanationIntent)


def parse_explore_explanation_intent(value: str | None) -> ExploreExplanationIntent:
    normalized = (value or "").strip()
    try:
        return ExploreExplanationIntent(normalized)
    except ValueError as exc:
        raise ExploreExplanationIntentError("Unknown Explore explanation question.") from exc


def build_explore_explanation_packet(
    destination: ExploreDestination,
    context: DestinationContext,
    *,
    intent: ExploreExplanationIntent,
    locale: str = "en",
) -> ExplanationPacket:
    spec = explore_explanation_intent_spec(intent)
    facts: list[GroundedFact] = [
        GroundedFact(
            id="destination_identity",
            statement=f"Reviewed destination scope: {destination.scope_label}.",
        ),
        GroundedFact(
            id="currency",
            statement=(
                "The current primary currency for this reviewed destination scope is "
                f"{destination.currency_code}."
            ),
        ),
        GroundedFact(
            id="as_of",
            statement=f"The reviewed Explore context is evaluated as of {context.as_of.isoformat()}.",
        ),
        GroundedFact(
            id="provenance_boundary",
            statement=(
                "Every local-price or payment fact in this packet comes from a reviewed record "
                "that passed the application's provenance checks; source links stay visible in "
                "Explore rather than being generated by AI."
            ),
        ),
        GroundedFact(
            id="reference_scope",
            statement=(
                "This is descriptive current destination money context, not an exchange-rate "
                "quote, historical purchasing-power measure, affordability ranking or complete "
                "cost-of-living index."
            ),
        ),
    ]

    for index, price in enumerate(context.prices[:3], start=1):
        amount = format(price.amount_low, "f")
        if price.amount_high is not None and price.amount_high != price.amount_low:
            amount = f"{amount} to {format(price.amount_high, 'f')}"
        facts.append(
            GroundedFact(
                id=f"price_{index}",
                statement=(
                    f"Reviewed local price anchor: {price.label} is {amount} "
                    f"{price.currency_code}. Scope: {price.scope_label}. "
                    f"Observed {price.observed_at.isoformat()}."
                ),
            )
        )

    if context.payment is not None:
        payment = context.payment
        payment_values = (
            ("payment_summary", "Reviewed payment summary", payment.summary),
            ("payment_cards", "Reviewed card guidance", payment.payment_customs),
            ("payment_cash", "Reviewed cash guidance", payment.cash_usage),
            ("payment_atm", "Reviewed cash-machine guidance", payment.atm_notes),
            ("payment_tipping", "Reviewed tipping guidance", payment.tipping),
            (
                "payment_dcc",
                "Reviewed dynamic-currency-conversion guidance",
                payment.dcc_warning,
            ),
        )
        for fact_id, label, value in payment_values:
            normalized = " ".join(value.split())
            if normalized:
                facts.append(
                    GroundedFact(
                        id=fact_id,
                        statement=f"{label}: {normalized}",
                    )
                )
        facts.append(
            GroundedFact(
                id="payment_verified",
                statement=(
                    "The reviewed payment guidance was verified on "
                    f"{payment.verified_at.date().isoformat()}."
                ),
            )
        )

    statements = tuple(fact.statement for fact in facts)
    dates = _ordered_unique(
        match
        for statement in statements
        for match in _DATE_RE.findall(statement)
    )
    text_without_dates = " ".join(_DATE_RE.sub("", statement) for statement in statements)
    numbers = _ordered_unique(
        value.replace(",", ".") for value in _NUMBER_RE.findall(text_without_dates)
    )
    currency_codes = (destination.currency_code,)
    uppercase_tokens = _ordered_unique(
        token
        for statement in statements
        for token in _UPPERCASE_RE.findall(statement)
        if token not in currency_codes
    )

    return ExplanationPacket(
        packet_version=PACKET_VERSION,
        locale=locale,
        intent_id=spec.intent.value,
        intent_question=spec.question,
        focus_instruction=spec.focus_instruction,
        required_fact_ids=spec.required_fact_ids,
        facts=tuple(facts),
        allowed_currencies=currency_codes,
        allowed_uppercase_tokens=uppercase_tokens,
        allowed_dates=dates,
        allowed_numbers=numbers,
    )


def build_explore_fallback_result(
    packet: ExplanationPacket,
    *,
    intent: ExploreExplanationIntent,
    reason: str,
) -> ExplanationResult:
    facts = {fact.id: fact for fact in packet.facts}
    identity = facts["destination_identity"]
    reference_scope = facts["reference_scope"]
    as_of = facts["as_of"]
    provenance = facts["provenance_boundary"]

    if intent is ExploreExplanationIntent.EVIDENCE:
        short_answer = _insight(as_of)
        factor_ids = ("provenance_boundary", "price_1", "payment_verified")
        next_step = ExplanationInsight(
            text=(
                "Check the source and observation details shown in Explore for the specific fact "
                "you plan to use."
            ),
            supporting_fact_ids=(provenance.id, as_of.id),
        )
    else:
        short_answer = _insight(identity)
        factor_ids = ("currency", "price_1", "payment_summary")
        next_step = ExplanationInsight(
            text=(
                "Use the canonical destination actions in Explore when you want to convert, "
                "compare or inspect the city profile."
            ),
            supporting_fact_ids=(identity.id, reference_scope.id),
        )

    key_factors = tuple(
        _insight(facts[fact_id])
        for fact_id in factor_ids
        if fact_id in facts
    )[:3]
    if not key_factors:
        key_factors = (_insight(provenance),)

    return ExplanationResult(
        short_answer=short_answer,
        key_factors=key_factors,
        watch_out_for=_insight(reference_scope),
        next_step=next_step,
        generated=False,
        source_label="Built-in explanation",
        fallback_reason=reason,
    )


def _insight(fact: GroundedFact) -> ExplanationInsight:
    return ExplanationInsight(text=fact.statement, supporting_fact_ids=(fact.id,))


def _ordered_unique(values) -> tuple[str, ...]:
    return tuple(dict.fromkeys(values))
