# Generated by Django 5.2.17 on 2026-10-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0007_saved_places_and_comparisons"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedscenario",
            name="budget_basis",
            field=models.CharField(
                choices=[
                    ("reference_conversion", "Reference conversion"),
                    ("payment_estimate", "Payment-adjusted estimate"),
                ],
                default="reference_conversion",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="savedscenario",
            name="planning_destination_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=12,
                max_digits=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="savedscenario",
            name="fx_markup_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="savedscenario",
            name="source_fixed_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=12,
                max_digits=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="savedscenario",
            name="destination_fixed_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=12,
                max_digits=40,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="savedscenario",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("budget_basis__in", ("reference_conversion", "payment_estimate"))
                ),
                name="scenario_budget_basis_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="savedscenario",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        ("budget_basis", "reference_conversion"),
                        ("planning_destination_amount__isnull", True),
                        ("fx_markup_percent__isnull", True),
                        ("source_fixed_fee__isnull", True),
                        ("destination_fixed_fee__isnull", True),
                    )
                    | models.Q(
                        ("budget_basis", "payment_estimate"),
                        ("planning_destination_amount__isnull", False),
                        ("planning_destination_amount__gte", 0),
                        ("fx_markup_percent__isnull", False),
                        ("fx_markup_percent__gte", 0),
                        ("fx_markup_percent__lte", 25),
                        ("source_fixed_fee__isnull", False),
                        ("source_fixed_fee__gte", 0),
                        ("destination_fixed_fee__isnull", False),
                        ("destination_fixed_fee__gte", 0),
                    )
                ),
                name="scenario_budget_basis_payload_valid",
            ),
        ),
    ]
