# Generated by Django 5.2.17 on 2026-10-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0008_saved_scenario_budget_basis"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedScenarioShoppingAssumptions",
            fields=[
                (
                    "scenario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="shopping_assumptions",
                        serialize=False,
                        to="travel.savedscenario",
                    ),
                ),
                (
                    "item_price",
                    models.DecimalField(decimal_places=12, max_digits=40),
                ),
                (
                    "shipping",
                    models.DecimalField(decimal_places=12, default=0, max_digits=40),
                ),
                (
                    "known_fees",
                    models.DecimalField(decimal_places=12, default=0, max_digits=40),
                ),
                (
                    "fx_markup_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("item_price__gt", 0)),
                        name="scenario_shop_item_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("shipping__gte", 0)),
                        name="scenario_shop_shipping_nonneg",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("known_fees__gte", 0)),
                        name="scenario_shop_fees_nonneg",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("fx_markup_percent__gte", 0),
                            ("fx_markup_percent__lte", 25),
                        ),
                        name="scenario_shop_markup_range",
                    ),
                ],
            },
        ),
    ]
