# Generated by Django 5.2.17 on 2026-10-04

import decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0009_saved_scenario_shopping_assumptions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetAssumptionPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("duration_days", models.PositiveSmallIntegerField()),
                ("travelers", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_assumption_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "name"),
                        name="unique_user_budget_preset_name",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("duration_days__gte", 1),
                            ("duration_days__lte", 365),
                        ),
                        name="budget_preset_duration_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("travelers__gte", 1),
                            ("travelers__lte", 20),
                        ),
                        name="budget_preset_travelers_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BudgetAssumptionPresetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("coffee", "Coffee"),
                            ("casual_meal", "Casual meal"),
                            ("transit", "Transit"),
                            ("groceries", "Groceries"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "units_per_person_per_day",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "preset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="travel.budgetassumptionpreset",
                    ),
                ),
            ],
            options={
                "ordering": ("category", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("preset", "category"),
                        name="unique_budget_preset_category",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("units_per_person_per_day__gte", decimal.Decimal("0.01")),
                            ("units_per_person_per_day__lte", 100),
                        ),
                        name="budget_preset_units_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "category__in",
                                (
                                    "coffee",
                                    "casual_meal",
                                    "transit",
                                    "groceries",
                                    "other",
                                ),
                            )
                        ),
                        name="budget_preset_category_allowed",
                    ),
                ],
            },
        ),
    ]
