# Generated by Django 5.2.17 on 2026-10-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0009_saved_scenario_shopping_assumptions"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScenarioNotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("pre_trip", "Pre-trip reminder"),
                            ("context_freshness", "Context/offline freshness"),
                            ("rate_alert", "Scenario rate alert"),
                        ],
                        max_length=24,
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("timezone", models.CharField(max_length=64)),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("once", "Once when due"),
                            ("daily", "At most daily"),
                            ("weekly", "At most weekly"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "delivery_channel",
                    models.CharField(
                        choices=[("in_app", "In-app")],
                        default="in_app",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to="travel.savedscenario",
                    ),
                ),
            ],
            options={
                "ordering": ("notification_type", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scenario", "notification_type"),
                        name="unique_scenario_notification_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "notification_type__in",
                                ("pre_trip", "context_freshness", "rate_alert"),
                            )
                        ),
                        name="scenario_notification_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("cadence__in", ("once", "daily", "weekly"))
                        ),
                        name="scenario_notification_cadence_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("delivery_channel__in", ("in_app",))),
                        name="scenario_notification_channel_valid",
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=["scenario", "enabled", "notification_type"],
                        name="travel_scn_notify_idx",
                    )
                ],
            },
        ),
    ]
