# Generated by Django 5.2 on 2026-10-04

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0010_scenario_notification_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenarionotificationpreference",
            name="last_delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scenarionotificationpreference",
            name="rate_change_threshold_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="scenarionotificationpreference",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("rate_change_threshold_percent__isnull", True))
                    | models.Q(
                        ("rate_change_threshold_percent__gte", Decimal("0.1")),
                        ("rate_change_threshold_percent__lte", Decimal("25")),
                    )
                ),
                name="scenario_notification_rate_threshold_range",
            ),
        ),
        migrations.CreateModel(
            name="ScenarioNotificationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dedupe_key", models.CharField(max_length=128)),
                ("title", models.CharField(max_length=160)),
                ("body", models.CharField(max_length=600)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "preference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="travel.scenarionotificationpreference",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("preference", "dedupe_key"),
                        name="unique_notification_delivery_dedupe",
                    )
                ],
                "indexes": [
                    models.Index(
                        fields=["preference", "-created_at"],
                        name="travel_notify_deliv_idx",
                    )
                ],
            },
        ),
    ]
